### ISSUE TITLE
No environment error tests

### ISSUE THREAD

**Issue by msKaleb** [gmarcha/pipexMedic#3]
Hi, can you give any hints for solving the NULL envp parameter? I get this output (I paste the test 2 output only):
```

      ERROR TEST
      NUMBER 2
      < input grep Hello | wc -l > output (No environment)


 - Bash output file:
1
\EOF

 - Pipex output file: None

 - Bash standard stream: None

 - Pipex standard stream: None

 - Bash exit code value: 0

 - Pipex exit code value: 11
```

**Comment by angelidito** [comment]
Did you find any solution @msKaleb?

i have a similar output:
```
      ERROR TEST
      NUMBER 2
      < input grep Hello | wc -l > output (No environment)


 - Bash output file:
       1
\EOF

 - Pipex output file: None

 - Bash standard stream: None

 - Pipex standard stream: None

 - Bash exit code value: 0

 - Pipex exit code value: 0
```

**Comment by gmarcha** [comment]
From your outputs, I can tell that: your program doesn't output a result while bash does and your program exit with a wrong status code (1); your program doesn't output a result while bash does - but exist statuses are matching (2).

When bash is started with an empty environment, it still can executes **programs** (i.e. file paths) AND **commands** because it populates PATH and HOME environment variables with default values. You can verify that behavior by trying to start a shell with an empty environment (in a non-existing directory to test HOME behavior).
